name: ME-bw
favicon: null
layout_spectrum: 0.04737
typography_spectrum: 0.86788
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#756148'
    - '#ffffff'
    - '#9b8458'
    - '#251b11'
    - '#baae94'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
